spring:
    datasource:
        url: jdbc:mysql://15.165.154.135:3306/hululuuuu?characterEncoding=UTF-8&serverTimezone=UTC
        username: yiyingroot
        password: 12341234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
        ddl-auto: create
    h2:
        console:
            enabled: true
        path: /console
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false